org: projectconnect
app: connect-server
service: express-lambda-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: production
  deploymentBucket:
    name: server32123
    serverSideEncryption: AES256
  httpApi:
    cors:
      allowedOrigins:
        - 'http://localhost:8080'
        - 'https://connect.vasubhut.com'
      allowedHeaders:
        - Content-Type
        - Authorization
      allowCredentials: true
  
functions:
  app:
    handler: app.handler 
    events:
      - httpApi: '*'

plugins:
  - serverless-offline 

package:
  patterns:
    - '!node_modules/.bin/**'
    - '!node_modules/.cache/**'
    - '!.git/**'
    - '!.github/**'
  individually: false  
  excludeDevDependencies: true

custom:
  webpack:
    packager: 'npm'
    includeModules: true  
  serverless-offline:
    noPrependStageInUrl: true
    ignoreJWTSignature: true
    useChildProcesses: true
    binaryMimeTypes: [] 
    noAuth: true
    httpPort: 5000
    babelOptions:
      presets: ["env"]